### ISSUE TITLE
Build system refactor

### ISSUE THREAD

**Issue by pdietl** [martonmiklos/STLINK-V3-BRIDGE_libusb#3]
How would you feel about porting the build system to [Meson](https://mesonbuild.com/)? I am willing to do that and adapt the example code to a CLI-based application if you're interested. Meson projects can also export a CMake config file to be used as a dependency in a CMake-based project.

**Comment by martonmiklos** [comment]
Deal! Portability/usability wise everything is better than qmake.

**Comment by martonmiklos** [comment]
Many thanks for your contribution @pdietl !
