### ISSUE TITLE
Protected branch

### ISSUE THREAD

**Issue by pdietl** [martonmiklos/STLINK-V3-BRIDGE_libusb#9]
@martonmiklos May I recommend that you:
* setup `master` as a protected branch that cannot be directly pushed to
* require passing Checks/Github Actions workflows for merging PRs
* require 1 reviewer to approve (if you so wish)

**Comment by martonmiklos** [comment]
Sure!

I think the settings are aligned with your request:
![kép](https://user-images.githubusercontent.com/1609182/232144608-58e41625-2e3d-47be-9c95-aaa3048021e8.png)
Let me know if I missed something.

And I deeply appreciate your work on this! I am very glad to see how the quick and dirty thrown together project evolved thanks to your work.

**Comment by pdietl** [comment]
Yes that looks good! You're super welcome.
